apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
spec:
  workspaces:
    - name: output
  params:
    - name: app-name
      type: string
    - name: build-image
      type: string
  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: git-clone
      taskRef:
        name: git-clone
      workspaces:
        - name: source
          workspace: output

    - name: lint
      taskRef:
        name: flake8-lint
      workspaces:
        - name: source
          workspace: output

    - name: run-tests
      taskRef:
        name: nose
      workspaces:
        - name: source
          workspace: output

    - name: build-image
      taskRef:
        name: buildah
      workspaces:
        - name: source
          workspace: output
      params:
        - name: IMAGE
          value: $(params.build-image)

    - name: deploy
      taskRef:
        name: openshift-client
      workspaces:
        - name: source
          workspace: output
      params:
        - name: SCRIPT
          value: |
            oc create deployment $(params.app-name) \
            --image=$(params.build-image) --dry-run=client -o yaml | oc apply -f -