apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  workspaces:
    - name: source

  steps:
    - name: remove
      image: alpine
      workingDir: $(workspaces.source.path)

      securityContext:
        runAsNonRoot: false
        runAsUser: 0

      env:
        - name: WORKSPACE_SOURCE_PATH
          value: $(workspaces.source.path)

      script: |
        #!/usr/bin/env sh
        set -eu
        echo "Removing all files from ${WORKSPACE_SOURCE_PATH} ..."

        if [ -d "${WORKSPACE_SOURCE_PATH}" ] ; then
          rm -rf "${WORKSPACE_SOURCE_PATH:?}"/*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/.[!.]*
          rm -rf "${WORKSPACE_SOURCE_PATH}"/..?*
        fi
